language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - cmake
      - cmake-data
      - libglew-dev
      - libfreetype6
      - libdevil-dev

